In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/human-genetic-data/genetic_data_train.csv
/kaggle/input/human-genetic-data/genetic_data_test.csv


In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

# Suppress all warnings
warnings.filterwarnings('ignore')


In [4]:
df = pd.read_csv("/kaggle/input/human-genetic-data/genetic_data_train.csv")

In [5]:
df.shape

(183, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183 entries, 0 to 182
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   PC1       183 non-null    float64
 1   PC2       183 non-null    float64
 2   PC3       183 non-null    float64
 3   PC4       183 non-null    float64
 4   PC5       183 non-null    float64
 5   PC6       183 non-null    float64
 6   PC7       183 non-null    float64
 7   PC8       183 non-null    float64
 8   PC9       183 non-null    float64
 9   PC10      183 non-null    float64
 10  Ancestry  183 non-null    object 
dtypes: float64(10), object(1)
memory usage: 15.9+ KB


In [7]:
df.isnull().sum()

PC1         0
PC2         0
PC3         0
PC4         0
PC5         0
PC6         0
PC7         0
PC8         0
PC9         0
PC10        0
Ancestry    0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df['Ancestry'].unique()

array(['African', 'European', 'EastAsian', 'Oceanian', 'NativeAmerican'],
      dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
df['Ancestry'] =  le.fit_transform(df['Ancestry'])

In [12]:
df['Ancestry'].unique()

array([0, 2, 1, 4, 3])

In [13]:
X = df.drop(columns=['Ancestry'])  
y = df['Ancestry']

In [14]:
X.shape , y.shape

((183, 10), (183,))

In [15]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(multi_class = 'ovr')

In [16]:
lr.fit(X,y)

LogisticRegression(multi_class='ovr')

In [17]:
test = pd.read_csv('/kaggle/input/human-genetic-data/genetic_data_test.csv')

In [18]:
test.shape

(111, 11)

In [19]:
test

PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0     2.517683  5.464283  9.067873 -4.965928 -0.741937  0.039785  0.573279   
1     6.077012  1.032867 -5.795883 -3.490064 -0.600204 -0.120803  1.243767   
2     1.016945 -2.913299  0.907702  1.233580 -1.983452  1.605964  2.674998   
3   -10.860926  2.545077  0.023950 -1.474450  0.372286 -2.609954 -2.794092   
4     4.790262  3.621650 -1.442221  5.459907 -0.864235 -2.591185 -0.062762   
..         ...       ...       ...       ...       ...       ...       ...   
106 -11.030349  1.712786 -1.392893 -0.163989  3.623641 -0.263645 -3.337796   
107  -7.994173  0.045333 -0.738547  0.189793 -2.545140 -0.332066  0.026289   
108  -8.874531  2.074620 -2.060999 -0.898143 -1.372896 -3.175091  2.325163   
109  -7.017063 -0.199721 -1.469538 -1.997714  1.892038 -1.880466 -3.278863   
110  -5.488129  0.406477 -0.852392  2.299789 -1.219706 -0.260295  0.204571   

          PC8       PC9      PC10         Ancestry  
0   -0.216918  2.454823 -0.671274          Unknown  
1    1.821390 -1.173053  2.442467          Unknown  
2   -0.732921 -2.157438 -0.671274          Unknown  
3    1.264747 -3.974644 -0.671274          Unknown  
4    0.515344  0.228729 -0.671274          Unknown  
..        ...       ...       ...              ...  
106  2.279226 -2.632659 -0.671274  AfricanAmerican  
107 -1.840944 -0.456438 -0.671274  AfricanAmerican  
108 -1.256258 -0.133253 -0.671274  AfricanAmerican  
109 -0.336890  0.042410 -0.671274  AfricanAmerican  
110  0.262224  0.802251 -0.671274  AfricanAmerican  

[111 rows x 11 columns]

In [20]:
X_test = test.drop(columns=['Ancestry'])
y_test = test['Ancestry']

In [21]:
y_test= le.fit_transform(y_test)

In [22]:
y_test

array([2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [23]:
y_pred = lr.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score,precision_score, recall_score,f1_score


In [25]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.4774774774774775
Precision: 0.20363382250174702
Recall: 0.24
F1 Score: 0.2105952380952381


In [26]:
from sklearn.metrics import classification_report,confusion_matrix
report = classification_report(y_pred, y_test)
print(confusion_matrix(y_pred,y_test))

print(report)

[[52  0  1  0  0]
 [ 0  0  1  0  0]
 [ 0 26  1  0  0]
 [ 0 28  1  0  0]
 [ 0  0  1  0  0]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        53
           1       0.00      0.00      0.00         1
           2       0.20      0.04      0.06        27
           3       0.00      0.00      0.00        29
           4       0.00      0.00      0.00         1

    accuracy                           0.48       111
   macro avg       0.24      0.20      0.21       111
weighted avg       0.53      0.48      0.49       111



## Hyperparameter tunning using gridsearch CV

In [27]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV


In [28]:
class_weight = [{0:w,1:y} for w in [1,10,50,100] for y in [1,10,50,100]]

In [29]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],  
    'solver': ['newton-cg', 'lbfgs', 'liblinear'],
    'class_weight': [{0:w,1:y} for w in [1,10,50,100] for y in [1,10,50,100]]
}

# Initialize the GridSearchCV
grid_search = GridSearchCV(estimator=LogisticRegression(multi_class='multinomial', max_iter=1000),
                           param_grid=param_grid ,cv=5, scoring='accuracy')

# Fit the grid search
grid_search.fit(X, y)

# Best parameters
print("Best parameters:", grid_search.best_params_)


Best parameters: {'C': 0.01, 'class_weight': {0: 1, 1: 1}, 'solver': 'newton-cg'}


In [30]:
y_pred  = grid_search.predict(X_test)

In [31]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.46846846846846846


In [32]:
from sklearn.metrics import classification_report,confusion_matrix
report = classification_report(y_pred, y_test)
print(confusion_matrix(y_pred,y_test))

print(report)

[[51  0  1  0  0]
 [ 0  0  1  0  0]
 [ 1 27  1  0  0]
 [ 0 27  1  0  0]
 [ 0  0  1  0  0]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        52
           1       0.00      0.00      0.00         1
           2       0.20      0.03      0.06        29
           3       0.00      0.00      0.00        28
           4       0.00      0.00      0.00         1

    accuracy                           0.47       111
   macro avg       0.24      0.20      0.21       111
weighted avg       0.51      0.47      0.47       111

