<a href="https://www.kaggle.com/code/quratulain20/naive-bayes-bernoullinb?scriptVersionId=196178462" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix

In [2]:
df = pd.read_csv("/kaggle/input/play-tennis/play_tennis.csv")

In [3]:
df.shape

(14, 6)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   day       14 non-null     object
 1   outlook   14 non-null     object
 2   temp      14 non-null     object
 3   humidity  14 non-null     object
 4   wind      14 non-null     object
 5   play      14 non-null     object
dtypes: object(6)
memory usage: 800.0+ bytes


In [5]:
df.head()

day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [6]:
df.columns

Index(['day', 'outlook', 'temp', 'humidity', 'wind', 'play'], dtype='object')

In [7]:
def unique(dataset):
    for i in dataset.columns:
        print(f"The unique value in'{i}':{dataset[i].unique()}")
    

In [8]:
unique(df)

The unique value in'day':['D1' 'D2' 'D3' 'D4' 'D5' 'D6' 'D7' 'D8' 'D9' 'D10' 'D11' 'D12' 'D13'
 'D14']
The unique value in'outlook':['Sunny' 'Overcast' 'Rain']
The unique value in'temp':['Hot' 'Mild' 'Cool']
The unique value in'humidity':['High' 'Normal']
The unique value in'wind':['Weak' 'Strong']
The unique value in'play':['No' 'Yes']


In [9]:
df_encoded = pd.get_dummies(df , drop_first=True)

In [10]:
df_encoded = df_encoded.astype(int)

In [11]:
X = df_encoded.iloc[:,:-1]
y = df_encoded.iloc[:,-1]

In [12]:
X.head()

day_D10  day_D11  day_D12  day_D13  day_D14  day_D2  day_D3  day_D4  \
0        0        0        0        0        0       0       0       0   
1        0        0        0        0        0       1       0       0   
2        0        0        0        0        0       0       1       0   
3        0        0        0        0        0       0       0       1   
4        0        0        0        0        0       0       0       0   

   day_D5  day_D6  day_D7  day_D8  day_D9  outlook_Rain  outlook_Sunny  \
0       0       0       0       0       0             0              1   
1       0       0       0       0       0             0              1   
2       0       0       0       0       0             0              0   
3       0       0       0       0       0             1              0   
4       1       0       0       0       0             1              0   

   temp_Hot  temp_Mild  humidity_Normal  wind_Weak  
0         1          0                0          1  
1         1          0                0          0  
2         1          0                0          1  
3         0          1                0          1  
4         0          0                1          1

In [13]:
y

0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0
Name: play_Yes, dtype: int64

In [14]:
X_train,X_test ,y_train,y_test = train_test_split(X,y, test_size=0.2 , random_state=42)
bnb = BernoulliNB()
model = bnb.fit(X_train,y_train)

In [15]:
y_pred = model.predict(X_test)

In [16]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[0 1]
 [1 1]]
0.3333333333333333


- By using one hot encoding we get very low accuracy let's try label encoder


In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for column in df.select_dtypes(include=['object']).columns:
    df[column] = le.fit_transform(df[column])

In [18]:
df.head()

day  outlook  temp  humidity  wind  play
0    0        2     1         0     1     0
1    6        2     1         0     0     0
2    7        0     1         0     1     1
3    8        1     2         0     1     1
4    9        1     0         1     1     1

In [19]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [20]:
X_train,X_test ,y_train,y_test = train_test_split(X,y, test_size=0.2 , random_state=42)
bnb = BernoulliNB()
model = bnb.fit(X_train,y_train)

In [21]:
y_pred = model.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[1 0]
 [0 2]]
1.0


### Calculating the probability of following scinarios


## Problem 1
> Outlook=sunny , Temperatue= Hot, Humidity= High ,Wind=Weak (probability of play nad not play)

In [22]:
df.columns

Index(['day', 'outlook', 'temp', 'humidity', 'wind', 'play'], dtype='object')

In [23]:
df['outlook'].unique()

array([2, 0, 1])

In [24]:
sunny_total = (df['outlook']== 'Sunny').sum()